# Generated by packaging/homebrew/render-formula.sh. Do not edit by hand:
# every release overwrites it with fresh URLs and checksums.
class Pinz < Formula
  desc "Spatial bulletin board in the terminal: post-it notes on a pannable, zoomable board"
  homepage "https://github.com/Gaurgle/pinz"
  version "0.6.1"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "https://github.com/Gaurgle/pinz/releases/download/v0.6.1/pinz-0.6.1-aarch64-apple-darwin.tar.gz"
      sha256 "e980f8f95f1d02eddb90e9be0c379e2ae97307f4f845ccecedbb680d5a305f81"
    end
    on_intel do
      url "https://github.com/Gaurgle/pinz/releases/download/v0.6.1/pinz-0.6.1-x86_64-apple-darwin.tar.gz"
      sha256 "c1054b64075ba4e5750b25cb7744fcfc6a662856dc7c39590a67b942d7493665"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Gaurgle/pinz/releases/download/v0.6.1/pinz-0.6.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "7764ffab2e36272496fc393395ee0fff62f292808c98bf8d112878eef957a408"
    end
  end

  def install
    bin.install "pinz"
  end

  test do
    # `pinz version` reaches the network to name the newest release, which a
    # test sandbox may not allow. `help` answers offline and still proves the
    # binary runs on this machine.
    assert_match "spatial bulletin board", shell_output("#{bin}/pinz help")
  end
end
