# Generated by packaging/homebrew/render-formula.sh. Do not edit by hand:
# every release overwrites it with fresh URLs and checksums.
class Pinz < Formula
  desc "Spatial bulletin board in the terminal: post-it notes on a pannable, zoomable board"
  homepage "https://github.com/Gaurgle/pinz"
  version "0.6.0"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "https://github.com/Gaurgle/pinz/releases/download/v0.6.0/pinz-0.6.0-aarch64-apple-darwin.tar.gz"
      sha256 "608e9eae7993fb8f6e9a5edb3691989daedcf3c9ec0c271fd2afb2196cdccbf2"
    end
    on_intel do
      url "https://github.com/Gaurgle/pinz/releases/download/v0.6.0/pinz-0.6.0-x86_64-apple-darwin.tar.gz"
      sha256 "5e37a1e0bd2b4b626e2f4d08b8e4fefb72d905dbc12112ae20e916b1c5b4c6d3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Gaurgle/pinz/releases/download/v0.6.0/pinz-0.6.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "591d8bf3935ab44214cbd384b5ab8eb9b9dc39a2e9decbabb869a4876392f1c5"
    end
  end

  def install
    bin.install "pinz"
  end

  test do
    # `pinz version` reaches the network to name the newest release, which a
    # test sandbox may not allow. `help` answers offline and still proves the
    # binary runs on this machine.
    assert_match "spatial bulletin board", shell_output("#{bin}/pinz help")
  end
end
